set(_AMENT_PACKAGE_NAME "crb_ros_msg")
set(crb_ros_msg_VERSION "0.1.0")
set(crb_ros_msg_MAINTAINER "CASBOT Team <casbot@todo.todo>")
set(crb_ros_msg_BUILD_DEPENDS "std_msgs" "sensor_msgs")
set(crb_ros_msg_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(crb_ros_msg_BUILD_EXPORT_DEPENDS "std_msgs" "sensor_msgs")
set(crb_ros_msg_BUILDTOOL_EXPORT_DEPENDS )
set(crb_ros_msg_EXEC_DEPENDS "std_msgs" "sensor_msgs")
set(crb_ros_msg_TEST_DEPENDS )
set(crb_ros_msg_GROUP_DEPENDS )
set(crb_ros_msg_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(crb_ros_msg_DEPRECATED "")
set(crb_ros_msg_EXPORT_TAGS)
list(APPEND crb_ros_msg_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
